version: '3'
services:
  web:
    build: frontend
    ports:
      - "8080:8080"

  backend:
    build: backend
    ports:
      - "5000:5000"
    #depends_on:
    #  - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0