services:
  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
    networks:
      - oiat-net

  # React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # default port
    depends_on:
      - mysql-db
    networks:
      - oiat-net

  # Python Flask
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000" # default port
    depends_on:
      - mysql-db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - oiat-net

  # MySQL Database
  mysql-db:
    # Using the latest version
    # Check here in future for updated versions of the image
    # https://hub.docker.com/_/mysql
    image: mysql:8.2
    # Configuration for the MySQL DB Password
    # This file should be stored on the server, not in the root of the web
    # This file should contain the password:
    # MYSQL_ROOT_PASSWORD=[password]
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: datababe # name of database
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306" # default port

    # Where persistent data should be stored on the server
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - oiat-net

# Specifies the persistent data that needs to be loaded
# In our case, it's just the MySQL database
volumes:
  mysql-data:

networks:
  oiat-net:
    driver: bridge